const $=id=>document.getElementById(id),canvas=$('drawing'),ctx=canvas.getContext('2d'),svg=$('coloring');
const colors=['#ff7399','#ffae62','#ffe16b','#7ccca0','#74b9ed','#ac8bd8','#845e49','#333948'];
let scene='cat',tool='fill',color=colors[0],history=[],future=[],stroke=null,hue=0,db,ready=false;
const scenes={cat:`<g stroke="#594137" stroke-width="5" stroke-linejoin="round"><path data-region="sky" d="M0 0H360V440H0Z" fill="white" stroke="none"/><path data-region="tail" d="M239 326Q324 339 296 259Q284 237 267 251Q254 264 273 280Q288 308 233 299Z" fill="white"/><ellipse data-region="body" cx="181" cy="307" rx="77" ry="83" fill="white"/><path data-region="head" d="M104 205 95 107 148 140Q180 127 213 140L266 107 257 205Q250 264 181 263Q112 264 104 205Z" fill="white"/><path data-region="ear1" d="m111 130 30 20-26 16Z" fill="white"/><path data-region="ear2" d="m250 130-30 20 26 16Z" fill="white"/><ellipse data-region="paw1" cx="144" cy="370" rx="29" ry="20" fill="white"/><ellipse data-region="paw2" cx="218" cy="370" rx="29" ry="20" fill="white"/><path data-region="bow1" d="m179 280-35-17v39Z" fill="white"/><path data-region="bow2" d="m181 280 35-17v39Z" fill="white"/><circle data-region="bow3" cx="180" cy="281" r="9" fill="white"/><g fill="none" stroke-linecap="round"><path d="M140 194q10-15 20 0m43 0q10-15 20 0m-54 29q11 15 22 0m-11-10v10M124 217l-29-6m29 19-29 5m143-18 29-6m-29 19 29 5"/></g><path d="m171 208 10 9 10-9Z" fill="#594137"/><path data-region="star" d="m57 55 7 17 19 1-15 12 5 19-16-10-17 10 5-19-15-12 20-1Z" fill="white"/><path data-region="heart" d="M292 63C264 38 249 72 292 99C335 72 320 38 292 63Z" fill="white"/></g>`,princess:`<g stroke="#594137" stroke-width="5" stroke-linejoin="round"><path data-region="sky" d="M0 0H360V440H0Z" fill="white" stroke="none"/><path data-region="hair" d="M119 170Q101 98 180 92Q261 98 244 170L258 266H103Z" fill="white"/><path data-region="arm1" d="m145 231-44 67q-8 20 8 24l55-62Z" fill="white"/><path data-region="arm2" d="m215 231 44 67q8 20-8 24l-55-62Z" fill="white"/><path data-region="dress" d="M148 265 82 389Q180 425 278 389L212 265Z" fill="white"/><path data-region="bodice" d="M141 221Q180 206 219 221L212 269H148Z" fill="white"/><path data-region="face" d="M126 144Q180 174 234 144V174Q232 223 180 226Q128 223 126 174Z" fill="white"/><path data-region="crown" d="m128 111-8-54 34 23 26-37 26 37 34-23-8 54Z" fill="white"/><circle data-region="gem" cx="180" cy="88" r="9" fill="white"/><path data-region="belt" d="M148 260H212V277H148Z" fill="white"/><path data-region="dresscenter" d="M170 278 139 400Q180 407 221 400L190 278Z" fill="white"/><g fill="none" stroke-linecap="round"><path d="m146 181q9-12 18 0m32 0q9-12 18 0m-47 21q13 12 26 0"/></g><path data-region="star" d="m51 173 6 15 17 1-13 11 4 17-14-9-15 9 4-17-13-11 17-1Z" fill="white"/><path data-region="heart" d="M302 141C274 116 259 150 302 177C345 150 330 116 302 141Z" fill="white"/></g>`,blank:''};
function snapshot(){return {scene,fills:[...svg.querySelectorAll('[data-region]')].map(e=>[e.dataset.region,e.getAttribute('fill')]),pixels:canvas.toDataURL()}}
function remember(){history.push(snapshot());if(history.length>20)history.shift();future=[];buttons()}
function buttons(){$('undo').disabled=!history.length;$('redo').disabled=!future.length}
function setTool(value){tool=value;canvas.style.pointerEvents=value==='fill'?'none':'auto';['fill','pen','rainbow','eraser'].forEach(t=>$(t).classList.toggle('active',t===value));$('fill').disabled=scene==='blank'}
async function restore(s){scene=s.scene;svg.innerHTML=scenes[scene];s.fills.forEach(([id,c])=>svg.querySelector(`[data-region="${id}"]`)?.setAttribute('fill',c));ctx.clearRect(0,0,720,880);if(s.pixels){const img=new Image();img.src=s.pixels;await img.decode();ctx.drawImage(img,0,0)}document.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('active',b.dataset.scene===scene));setTool(scene==='blank'&&tool==='fill'?'pen':tool);buttons();}
function request(store,mode,action){return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode);let result;const req=action(tx.objectStore(store));req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function save(){if(!ready||!db)return;try{await request('state','readwrite',s=>s.put(snapshot(),'current'));$('hint').textContent='已保存到這台手機 ✦'}catch{$('hint').textContent='儲存空間不足，請用「存成圖片」保存作品'}}
async function exportImage(){const out=document.createElement('canvas');out.width=720;out.height=880;const c=out.getContext('2d');c.fillStyle='white';c.fillRect(0,0,720,880);if(scene!=='blank'){const copy=svg.cloneNode(true);copy.setAttribute('xmlns','http://www.w3.org/2000/svg');const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(copy));await img.decode();c.drawImage(img,0,0,720,880)}c.drawImage(canvas,0,0);return out.toDataURL('image/png')}
async function keepArtwork(){if(!ready||!db)return;try{const image=await exportImage();await request('art','readwrite',s=>s.put({id:Date.now(),image}));const all=await request('art','readonly',s=>s.getAll());for(const old of all.sort((a,b)=>b.id-a.id).slice(20))await request('art','readwrite',s=>s.delete(old.id))}catch{$('hint').textContent='相簿儲存失敗，請先下載圖片'}}
colors.forEach((c,i)=>{const b=document.createElement('button');b.style.background=c;b.setAttribute('aria-label',['粉紅','橘','黃','綠','藍','紫','棕','黑'][i]);b.onclick=()=>{color=c;document.querySelectorAll('#palette button').forEach(x=>x.classList.toggle('active',x===b))};$('palette').append(b)});$('palette').firstChild.classList.add('active');
svg.addEventListener('pointerdown',e=>{const region=e.target.closest('[data-region]');if(!ready||tool!=='fill'||!region||region.getAttribute('fill')===color)return;remember();region.setAttribute('fill',color);save()});
function point(e){const r=canvas.getBoundingClientRect();const scale=Math.min(r.width/720,r.height/880);return {x:(e.clientX-r.left-(r.width-720*scale)/2)/scale,y:(e.clientY-r.top-(r.height-880*scale)/2)/scale}}
// Match the SVG's contain layout so strokes align with its regions.
canvas.style.objectFit='contain';
function mark(p,previous){ctx.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';ctx.strokeStyle=ctx.fillStyle=tool==='rainbow'?`hsl(${hue++*5%360} 85% 65%)`:color;ctx.lineWidth=+$('size').value*2;ctx.lineCap=ctx.lineJoin='round';ctx.beginPath();if(previous){ctx.moveTo(previous.x,previous.y);ctx.lineTo(p.x,p.y);ctx.stroke()}else{ctx.arc(p.x,p.y,ctx.lineWidth/2,0,Math.PI*2);ctx.fill()}ctx.globalCompositeOperation='source-over'}
canvas.onpointerdown=e=>{if(!ready||stroke)return;remember();canvas.setPointerCapture(e.pointerId);stroke={id:e.pointerId,p:point(e)};mark(stroke.p)};canvas.onpointermove=e=>{if(!stroke||stroke.id!==e.pointerId)return;for(const sample of e.getCoalescedEvents?.()||[e]){const p=point(sample);mark(p,stroke.p);stroke.p=p}};function finish(e){if(stroke?.id!==e.pointerId)return;stroke=null;save()}canvas.onpointerup=finish;canvas.onpointercancel=finish;
['fill','pen','rainbow','eraser'].forEach(t=>$(t).onclick=()=>setTool(t));
$('custom').oninput=e=>{color=e.target.value;document.querySelectorAll('#palette button').forEach(b=>b.classList.remove('active'))};
let busy=false;async function travel(from,to){if(busy||!from.length)return;busy=true;to.push(snapshot());await restore(from.pop());await save();busy=false}
$('undo').onclick=()=>travel(history,future);$('redo').onclick=()=>travel(future,history);
document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=async()=>{if(busy||!ready||b.dataset.scene===scene)return;busy=true;await keepArtwork();remember();await restore({scene:b.dataset.scene,fills:[],pixels:null});setTool(scene==='blank'?'pen':'fill');await save();busy=false});
$('clear').onclick=async()=>{if(busy||!ready)return;busy=true;await keepArtwork();remember();ctx.clearRect(0,0,720,880);svg.querySelectorAll('[data-region]').forEach(e=>e.setAttribute('fill','white'));await save();busy=false};
$('more').onclick=()=>{$('extras').hidden=!$('extras').hidden};$('download').onclick=async()=>{const a=document.createElement('a');a.href=await exportImage();a.download='小小畫室.png';a.click()};
$('gallery').onclick=async()=>{if(!ready||!db){$('hint').textContent='相簿無法保存，請下載圖片';return}await keepArtwork();const all=await request('art','readonly',s=>s.getAll());$('artworks').replaceChildren();for(const art of all.sort((a,b)=>b.id-a.id)){const a=document.createElement('a');a.href=art.image;a.download='小小畫室-'+art.id+'.png';const img=new Image();img.src=art.image;img.alt='我的畫作';a.append(img);$('artworks').append(a)}$('album').showModal()};$('close').onclick=()=>$('album').close();
async function init(){await restore({scene:'cat',fills:[]});try{db=await new Promise((resolve,reject)=>{const r=indexedDB.open('little-art-studio',1);r.onupgradeneeded=()=>{r.result.createObjectStore('state');r.result.createObjectStore('art',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const s=await request('state','readonly',x=>x.get('current'));if(s)await restore(s);ready=true}catch{ready=true;$('hint').textContent='此瀏覽器無法保存，畫完請下載圖片'}}
init();document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
