const $=id=>document.getElementById(id),canvas=$('drawing'),ctx=canvas.getContext('2d'),svg=$('coloring');
const colors=['#ff7399','#ffae62','#ffe16b','#7ccca0','#74b9ed','#ac8bd8','#f4b7ce','#cde9c4','#845e49','#333948','#ffffff','#e95c57','#e0a23e','#358a6c','#476cbb'];
let masks=new Map(); const ink=document.createElement('canvas');ink.width=720;ink.height=880;const inkCtx=ink.getContext('2d');
let scene='cat',tool='fill',color=colors[0],history=[],future=[],stroke=null,hue=0,db,ready=false;
const scenes={cat:`<g stroke="#594137" stroke-width="5" stroke-linejoin="round"><path data-region="sky" d="M0 0H360V440H0Z" fill="white" stroke="none"/><path data-region="tail" d="M239 326Q324 339 296 259Q284 237 267 251Q254 264 273 280Q288 308 233 299Z" fill="white"/><ellipse data-region="body" cx="181" cy="307" rx="77" ry="83" fill="white"/><path data-region="head" d="M104 205 95 107 148 140Q180 127 213 140L266 107 257 205Q250 264 181 263Q112 264 104 205Z" fill="white"/><path data-region="ear1" d="m111 130 30 20-26 16Z" fill="white"/><path data-region="ear2" d="m250 130-30 20 26 16Z" fill="white"/><ellipse data-region="paw1" cx="144" cy="370" rx="29" ry="20" fill="white"/><ellipse data-region="paw2" cx="218" cy="370" rx="29" ry="20" fill="white"/><path data-region="bow1" d="m179 280-35-17v39Z" fill="white"/><path data-region="bow2" d="m181 280 35-17v39Z" fill="white"/><circle data-region="bow3" cx="180" cy="281" r="9" fill="white"/><g fill="none" stroke-linecap="round"><path d="M140 194q10-15 20 0m43 0q10-15 20 0m-54 29q11 15 22 0m-11-10v10M124 217l-29-6m29 19-29 5m143-18 29-6m-29 19 29 5"/></g><path d="m171 208 10 9 10-9Z" fill="#594137"/><path data-region="star" d="m57 55 7 17 19 1-15 12 5 19-16-10-17 10 5-19-15-12 20-1Z" fill="white"/><path data-region="heart" d="M292 63C264 38 249 72 292 99C335 72 320 38 292 63Z" fill="white"/></g>`,princess:`<g stroke="#594137" stroke-width="5" stroke-linejoin="round"><path data-region="sky" d="M0 0H360V440H0Z" fill="white" stroke="none"/><path data-region="hair" d="M119 170Q101 98 180 92Q261 98 244 170L258 266H103Z" fill="white"/><path data-region="arm1" d="m145 231-44 67q-8 20 8 24l55-62Z" fill="white"/><path data-region="arm2" d="m215 231 44 67q8 20-8 24l-55-62Z" fill="white"/><path data-region="dress" d="M148 265 82 389Q180 425 278 389L212 265Z" fill="white"/><path data-region="bodice" d="M141 221Q180 206 219 221L212 269H148Z" fill="white"/><path data-region="face" d="M126 144Q180 174 234 144V174Q232 223 180 226Q128 223 126 174Z" fill="white"/><path data-region="crown" d="m128 111-8-54 34 23 26-37 26 37 34-23-8 54Z" fill="white"/><circle data-region="gem" cx="180" cy="88" r="9" fill="white"/><path data-region="belt" d="M148 260H212V277H148Z" fill="white"/><path data-region="dresscenter" d="M170 278 139 400Q180 407 221 400L190 278Z" fill="white"/><g fill="none" stroke-linecap="round"><path d="m146 181q9-12 18 0m32 0q9-12 18 0m-47 21q13 12 26 0"/></g><path data-region="star" d="m51 173 6 15 17 1-13 11 4 17-14-9-15 9 4-17-13-11 17-1Z" fill="white"/><path data-region="heart" d="M302 141C274 116 259 150 302 177C345 150 330 116 302 141Z" fill="white"/></g>`,blank:''};
const blankPreview='<svg viewBox="0 0 100 100" fill="none"><path d="M18 70Q30 22 43 53T80 33" stroke="#ff7399" stroke-width="9" stroke-linecap="round"/><path d="M22 82Q49 54 77 72" stroke="#ac8bd8" stroke-width="8" stroke-linecap="round"/></svg>';
for(const name of ['cat','princess','blank']){const b=document.createElement('button');b.dataset.scene=name;b.setAttribute('aria-label',{cat:'貓咪',princess:'公主',blank:'空白畫布'}[name]);b.innerHTML=name==='blank'?blankPreview:`<svg viewBox="0 0 360 440">${scenes[name]}</svg>`;$('home-grid').append(b)}
function showEditor(){document.body.classList.remove('at-home');location.hash='draw'}
function showHome(){document.body.classList.add('at-home');save()}
$('home-back').onclick=()=>{if(busy||stroke)return;showHome();if(location.hash)historyBack()};
function historyBack(){window.history.replaceState(null,'',location.pathname+location.search)}
window.addEventListener('hashchange',()=>{if(!location.hash)showHome()});
function surfaceGeometry(){const home=document.body.classList.contains('at-home');if(home)document.body.classList.remove('at-home');const r=canvas.getBoundingClientRect();if(home)document.body.classList.add('at-home');const ratio=r.width/r.height;const w=Math.max(360,440*ratio),h=Math.max(440,360/ratio);return {x:(360-w)/2,y:(440-h)/2,w,h}}
let surface;
function prepareCopy(copy){copy.setAttribute('viewBox',`${surface.x} ${surface.y} ${surface.w} ${surface.h}`);copy.setAttribute('preserveAspectRatio','none');copy.setAttribute('width',canvas.width);copy.setAttribute('height',canvas.height);const sky=copy.querySelector('[data-region="sky"]');if(sky)sky.setAttribute('d',`M${surface.x} ${surface.y}h${surface.w}v${surface.h}h${-surface.w}Z`);return copy}
function snapshot(){return {scene,surface,width:canvas.width,height:canvas.height,fills:[...svg.querySelectorAll('[data-region]')].map(e=>[e.dataset.region,e.getAttribute('fill')]),pixels:canvas.toDataURL()}}
function remember(){history.push(snapshot());if(history.length>20)history.shift();future=[];buttons()}
function buttons(){$('undo').disabled=!history.length;$('redo').disabled=!future.length}
function setTool(value){tool=value;canvas.style.pointerEvents=value==='fill'?'none':'auto';['fill','pen','rainbow','eraser'].forEach(t=>$(t).classList.toggle('active',t===value));$('fill').disabled=scene==='blank';$('pen').classList.toggle('active',value==='pen'||value==='rainbow');$('color-open').classList.toggle('rainbow',value==='rainbow')}
async function restore(s){scene=s.scene;canvas.style.objectFit='fill';surface=surfaceGeometry();canvas.height=Math.round(720*surface.h/surface.w);ink.height=canvas.height;svg.innerHTML=scenes[scene];prepareCopy(svg);s.fills.forEach(([id,c])=>svg.querySelector(`[data-region="${id}"]`)?.setAttribute('fill',c));ctx.clearRect(0,0,canvas.width,canvas.height);if(s.pixels){const img=new Image();img.src=s.pixels;await img.decode();if(s.surface){const scale=canvas.width/surface.w;ctx.drawImage(img,(s.surface.x-surface.x)*scale,(s.surface.y-surface.y)*scale,s.surface.w*scale,s.surface.h*scale)}else if(scene==='blank'){ctx.drawImage(img,0,0,canvas.width,canvas.height)}else{const scale=Math.min(canvas.width/720,canvas.height/880);ctx.drawImage(img,(canvas.width-720*scale)/2,(canvas.height-880*scale)/2,720*scale,880*scale)}}document.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('active',b.dataset.scene===scene));setTool(scene==='blank'&&tool==='fill'?'pen':tool);buttons();await buildMasks();}
function request(store,mode,action){return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode);let result;const req=action(tx.objectStore(store));req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function save(){if(!ready||!db)return;try{await request('state','readwrite',s=>s.put(snapshot(),'current'));$('hint').textContent='已保存到這台手機 ✦'}catch{$('hint').textContent='儲存空間不足，請用「存成圖片」保存作品'}}
async function exportImage(){const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const c=out.getContext('2d');c.fillStyle='white';c.fillRect(0,0,canvas.width,canvas.height);if(scene!=='blank'){const copy=prepareCopy(svg.cloneNode(true));copy.setAttribute('xmlns','http://www.w3.org/2000/svg');const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(copy));await img.decode();c.drawImage(img,0,0,canvas.width,canvas.height)}c.drawImage(canvas,0,0);return out.toDataURL('image/png')}
async function keepArtwork(){if(!ready||!db)return;try{const image=await exportImage();await request('art','readwrite',s=>s.put({id:Date.now(),image}));const all=await request('art','readonly',s=>s.getAll());for(const old of all.sort((a,b)=>b.id-a.id).slice(20))await request('art','readwrite',s=>s.delete(old.id))}catch{$('hint').textContent='相簿儲存失敗，請先下載圖片'}}
function chooseColor(c){color=c;$('color-preview').style.background=c;document.querySelectorAll('#palette button').forEach(b=>b.classList.toggle('active',b.dataset.color===c));if(tool==='rainbow')setTool('pen');$('color-modal').close()}
colors.forEach((c,i)=>{const b=document.createElement('button');b.dataset.color=c;b.style.background=c;b.setAttribute('aria-label',['粉紅','橘','黃','綠','藍','紫','淡粉','淡綠','棕','黑','白','紅','金黃','深綠','深藍'][i]);b.onclick=()=>chooseColor(c);$('palette').append(b)});$('palette').firstChild.classList.add('active');
$('color-open').onclick=()=>$('color-modal').showModal();document.querySelectorAll('.dismiss').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
function mixedColor(){return `hsl(${$('hue').value} ${$('saturation').value}% ${$('lightness').value}%)`}
['hue','saturation','lightness'].forEach(id=>$(id).oninput=()=>{$('mix-preview').style.background=mixedColor()});$('mix-preview').style.background=mixedColor();$('use-color').onclick=()=>chooseColor(mixedColor());
const icons={fill:'<path d="m8 3 10 10-8 8-8-8 8-8m-4 8h14M19 17s3 3 3 4a3 3 0 0 1-6 0c0-1 3-4 3-4Z"/>',pen:'<path d="m15 3 6 6-12 12H3v-6Zm-9 9 6 6M14 4l6 6"/>',eraser:'<path d="m14 3 8 8-11 11H5l-4-4Zm-8 9 8 8M11 22h12"/>',undo:'<path d="M8 5 3 10l5 5M3 10h11a7 7 0 0 1 0 14" transform="translate(0 -3)"/>',more:'<circle cx="4" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="20" cy="12" r="1"/>'};Object.entries(icons).forEach(([id,path])=>$(id).querySelector('.tool-icon').innerHTML=`<svg viewBox="0 0 26 26" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${path}</svg>`);
async function buildMasks(){masks=new Map();if(scene==='blank')return;const regions=[...svg.querySelectorAll('[data-region]')];await Promise.all(regions.map(async region=>{const copy=prepareCopy(svg.cloneNode(true));copy.setAttribute('xmlns','http://www.w3.org/2000/svg');copy.querySelectorAll('g,path,ellipse,circle').forEach(el=>{el.setAttribute('stroke','#000');if(el.getAttribute('fill')!=='none')el.setAttribute('fill','#000')});copy.querySelector(`[data-region="${region.dataset.region}"]`).setAttribute('fill','#fff');const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(copy));await img.decode();const mask=document.createElement('canvas');mask.width=canvas.width;mask.height=canvas.height;const c=mask.getContext('2d');c.drawImage(img,0,0,canvas.width,canvas.height);const pixels=c.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<pixels.data.length;i+=4)pixels.data[i+3]=pixels.data[i];c.putImageData(pixels,0,0);masks.set(region.dataset.region,mask)}))}
function startRegion(p){if(scene==='blank')return null;const at=new DOMPoint(surface.x+p.x/canvas.width*surface.w,surface.y+p.y/canvas.height*surface.h);return [...svg.querySelectorAll('[data-region]')].reverse().find(el=>el.isPointInFill(at))?.dataset.region||'sky'}
svg.addEventListener('pointerdown',e=>{const region=e.target.closest('[data-region]');if(!ready||busy||tool!=='fill'||!region||region.getAttribute('fill')===color)return;remember();region.setAttribute('fill',color);save()});
function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.style.objectFit='fill';
function mark(p,previous){inkCtx.clearRect(0,0,canvas.width,canvas.height);inkCtx.globalCompositeOperation='source-over';inkCtx.strokeStyle=inkCtx.fillStyle=tool==='rainbow'?`hsl(${hue++*5%360} 85% 65%)`:color;inkCtx.lineWidth=+$('size').value*2;inkCtx.lineCap=inkCtx.lineJoin='round';inkCtx.beginPath();if(previous){inkCtx.moveTo(previous.x,previous.y);inkCtx.lineTo(p.x,p.y);inkCtx.stroke()}else{inkCtx.arc(p.x,p.y,inkCtx.lineWidth/2,0,Math.PI*2);inkCtx.fill()}if(stroke.region){inkCtx.globalCompositeOperation='destination-in';inkCtx.drawImage(masks.get(stroke.region),0,0);inkCtx.globalCompositeOperation='source-over'}ctx.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';ctx.drawImage(ink,0,0);ctx.globalCompositeOperation='source-over'}
canvas.onpointerdown=e=>{if(!ready||busy||stroke)return;const p=point(e),region=startRegion(p);if(scene!=='blank'&&!masks.has(region))return;remember();canvas.setPointerCapture(e.pointerId);stroke={id:e.pointerId,p,region};mark(stroke.p)};canvas.onpointermove=e=>{if(!stroke||stroke.id!==e.pointerId)return;for(const sample of e.getCoalescedEvents?.()||[e]){const p=point(sample);mark(p,stroke.p);stroke.p=p}};function finish(e){if(stroke?.id!==e.pointerId)return;stroke=null;save()}canvas.onpointerup=finish;canvas.onpointercancel=finish;
['fill','pen','eraser'].forEach(t=>$(t).onclick=()=>setTool(t));$('rainbow').onclick=()=>{setTool('rainbow');$('color-modal').close()};
let busy=false;async function travel(from,to){if(busy||!from.length)return;busy=true;to.push(snapshot());await restore(from.pop());await save();busy=false}
$('undo').onclick=()=>travel(history,future);$('redo').onclick=()=>travel(future,history);
document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=async()=>{if(busy||!ready)return;if(b.dataset.scene===scene){showEditor();return;}busy=true;await keepArtwork();remember();await restore({scene:b.dataset.scene,fills:[],pixels:null});setTool(scene==='blank'?'pen':'fill');await save();busy=false;showEditor()});
$('clear').onclick=async()=>{if(busy||!ready)return;busy=true;await keepArtwork();remember();ctx.clearRect(0,0,canvas.width,canvas.height);svg.querySelectorAll('[data-region]').forEach(e=>e.setAttribute('fill','white'));await save();busy=false};
$('more').onclick=()=>$('tool-modal').showModal();$('download').onclick=async()=>{const a=document.createElement('a');a.href=await exportImage();a.download='小小畫室.png';a.click()};
$('gallery').onclick=async()=>{if(!ready||!db){$('hint').textContent='相簿無法保存，請下載圖片';return}await keepArtwork();const all=await request('art','readonly',s=>s.getAll());$('artworks').replaceChildren();for(const art of all.sort((a,b)=>b.id-a.id)){const a=document.createElement('a');a.href=art.image;a.download='小小畫室-'+art.id+'.png';const img=new Image();img.src=art.image;img.alt='我的畫作';a.append(img);$('artworks').append(a)}$('album').showModal()};$('close').onclick=()=>$('album').close();
async function init(){await restore({scene:'cat',fills:[]});try{db=await new Promise((resolve,reject)=>{const r=indexedDB.open('little-art-studio',1);r.onupgradeneeded=()=>{r.result.createObjectStore('state');r.result.createObjectStore('art',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const s=await request('state','readonly',x=>x.get('current'));if(s)await restore(s);ready=true}catch{ready=true;$('hint').textContent='此瀏覽器無法保存，畫完請下載圖片'}}
init();document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});

window.addEventListener('resize',async()=>{if(!ready||busy||stroke)return;busy=true;const s=snapshot();await restore(s);await save();busy=false});
