"""Stamp the release version everywhere and build the offline shell list.

release.json holds the single source of truth: a semantic version such as
1.0.0-beta.1 or 1.2.0. This script copies it into package.json and the
lockfile, module URLs (?v=), index.html (asset URLs and the version shown in
the about dialog) and offline-shell.js (the service worker cache name).
"""
from pathlib import Path
import json
import re

root = Path(__file__).resolve().parents[1]
version = json.loads((root / 'release.json').read_text())['version']
assert re.fullmatch(r'(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(alpha|beta|rc)\.[1-9]\d*)?', str(version)), \
    f'release.json version must look like 1.2.3 or 1.0.0-beta.1, not {version!r}'
stamp = r'\?v=[0-9A-Za-z.-]+'

for file in [root / 'app.js', *sorted((root / 'modules').glob('*.js'))]:
    text = file.read_text()
    text = re.sub(r"(from ['\"])(\.{1,2}/[^'\"?]+\.js)(?:" + stamp + r")?(['\"])",
                  lambda m: f'{m[1]}{m[2]}?v={version}{m[3]}', text)
    file.write_text(text)

html = root / 'index.html'
text = re.sub(stamp, f'?v={version}', html.read_text())
text = re.sub(r'(<span data-release>)[^<]*(</span>)', rf'\g<1>v{version}\g<2>', text)
html.write_text(text)

package = root / 'package.json'
data = json.loads(package.read_text())
data['version'] = version
package.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n')
lock = root / 'package-lock.json'
data = json.loads(lock.read_text())
data['version'] = data['packages']['']['version'] = version
lock.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n')

files = ['./', './index.html', f'./style.css?v={version}', f'./app.js?v={version}',
         './manifest.json', './icon.svg', f'./assets/coloring/catalog.js?v={version}']
files.extend(f'./modules/{f.name}?v={version}' for f in sorted((root / 'modules').glob('*.js')))
files.extend('./' + str(f.relative_to(root)) for f in sorted((root / 'assets/ui').iterdir()) if f.suffix in ('.svg', '.png'))
(root / 'offline-shell.js').write_text('// Generated by scripts/prepare-release.py\n'
    f'const SHELL_VERSION={json.dumps(version)};\nconst SHELL_FILES=' + json.dumps(files) + ';\n')
print(f'Prepared release {version}: {len(files)} shell files')
