"""Stamp local module URLs and build a project-scoped offline shell list."""
from pathlib import Path
import json
import re

root = Path(__file__).resolve().parents[1]
version = json.loads((root / 'release.json').read_text())['version']
for file in [root / 'app.js', *sorted((root / 'modules').glob('*.js'))]:
    text = file.read_text()
    text = re.sub(r"(from ['\"])(\.{1,2}/[^'\"?]+\.js)(?:\?v=\d+)?(['\"])",
                  lambda m: f'{m[1]}{m[2]}?v={version}{m[3]}', text)
    text = re.sub(r"const ASSET_VERSION\s*=\s*['\"]\d+['\"]", f"const ASSET_VERSION='{version}'", text)
    file.write_text(text)
html = root / 'index.html'
html.write_text(re.sub(r'\?v=\d+', f'?v={version}', html.read_text()))
files = ['./', './index.html', f'./style.css?v={version}', f'./app.js?v={version}',
         './manifest.json', './icon.svg', f'./assets/coloring/catalog.js?v={version}']
files.extend(f'./modules/{f.name}?v={version}' for f in sorted((root / 'modules').glob('*.js')))
files.extend('./' + str(f.relative_to(root)) for f in sorted((root / 'assets/ui').iterdir()) if f.suffix in ('.svg', '.png'))
(root / 'offline-shell.js').write_text('// Generated by scripts/prepare-release.py\n'
    f'const SHELL_VERSION={version};\nconst SHELL_FILES=' + json.dumps(files) + ';\n')
print(f'Prepared release {version}: {len(files)} shell files')
